### ISSUE TITLE
Dwoo_Exception

### ISSUE THREAD

**Issue by feathersanddown** [philsturgeon/codeigniter-dwoo#1]
I get this when i try to parse {elapsed_time} inside  welcome_message.php view file from a fresh CI installation. If I remove it, the page is rendered,

An Error Was Encountered
exception 'Dwoo_Exception' with message 'Plugin elapsed_time can not be found, maybe you forgot to bind it if it's a custom plugin ?

.. and then the stack trace..

maybe I need some custom configuration or add another file that have functions that load and execute '{function_name}'. Add a 'function_name' to $config['parser_allowed_php_functions']  not work.

Thanks in advance

**Comment by philsturgeon** [comment]
I've added some support for these into master.

**Comment by feathersanddown** [comment]
Still can't make it work. I can't find '$this->_ci->output->parse_exec_vars' variable (line 172), neither in pyrocms exist. I'm asking why is needed to add it at code library, isn't library mission to run code inside {} marks and with it is enough? or those vars are special or run outside parser scope?.

and sorry for to be obstinate.

**Comment by feathersanddown** [comment]
Hi, it's me again... I've added some code and copy pasted another from PyroCMS.

First... i've commented the 'if' sentence at line 172 and at least it pass.

What i wanted to do is to parse a self made theme for PyroCMS 0.9.x series and i've found some inconveniences. To get my theme partially loaded (because its call functions not implemented (used in pyro) ) i have do the following steps:

a) Add your 'template', 'dwoo' and 'asset' library to use helpers/libraries functions
b) How still don't work, i have to copy/paste your theme_helper from themes module and edit it as $this->settings is a variable from settings module that I (still) not use. For the moment a hardcoded value do the trick.
c) Add 'theme_view', 'theme_js', 'theme_css' values to your dwoo 'parser.php' config file at line 76.

Your libraries are so great, that's what I have been searched for a long time, and I don't know if possible to your 'theme_view( )' function inside template or dwoo library because split theme in file aparts do with a single call is a desired feature for 'divide and conquer' practice.

Thank you =)

**Comment by philsturgeon** [comment]
I don't know what is getting you so confused. {elapse_time} and memory usage are nothing to do with Parser or Dwoo and never have been. They are part of the output class which is why they are treated differently.

I've used this code on MizuCMS and it works fine. As for the rest of your questions I have no idea what you are talkig about. {$settings->foo} works fine as does {theme_view()}.
