### ISSUE TITLE
Cannot access protected property MY_Loader::$_ci_cached_vars

### ISSUE THREAD

**Issue by carlotrimarchi** [philsturgeon/codeigniter-dwoo#11]
Hi,
I'm trying to use the Codeigniter Template library (Phil Sturgeon's one), infact I posted this error in the repo for that library, but it's a dwoo related error.

It happens that when I try to run the dwoo_test I get this error:

> PHP Fatal error:  Cannot access protected property MY_Loader::$_ci_cached_vars in /home/carlo/public_html/website/application/libraries/MY_Parser.php on line 146

On line 146 there's this:

```$data = array_merge($data, $this->_ci->load->_ci_cached_vars);

```
I'm using the last CodeIgniter version downloaded from github.

Any ideas?
```

**Comment by elrafael** [comment]
What's your CI version?

I'm using CI 2.1.0 and here it's working fine.

**Comment by andrefrcastro** [comment]
+1

Version 2.1.0

> Fatal error: Cannot access protected property CI_Loader::$_ci_cached_vars in \libraries\MY_Parser.php on line 146

**Comment by elrafael** [comment]
Sorry for late answer.

My bad, I'm using Modular extensions, already have this variable set as `public`.

In fact, new versions of CI have theses variables protected. You can extend the Loader class and change this variable to public, like that:

```
MY_Loader extends CI_Loader {
  public $_ci_cached_vars = array();
}
```

**Comment by hafizbistar** [comment]
well.. ci_smarty had the same problem.
https://github.com/Vheissu/Ci-Smarty/commit/1d825e4743f130b86815a5c7a27ba8e914170968

instead of making it public, they simply remove the whole line. possibly, its best just to keep it protected.

**Comment by yerbol777** [comment]
elrafael, thank you, you saved me. your solution worked for me.
