### ISSUE TITLE
Extends, Includes, and other function not work

### ISSUE THREAD

**Issue by devmohsh** [philsturgeon/codeigniter-dwoo#12]
Hi,

did you ever test to use these functions?
http://wiki.dwoo.org/index.php/Functions:include
http://wiki.dwoo.org/index.php/Functions:extends

the did not work while using "codeigniter-dwoo"

i try to use the official integration from dwoo itself and it work fine, but i need it in the parser based library
can you fix it please?

Regards

**Comment by elrafael** [comment]
Indeed.

But why don't you try as CI standards?

```
//Your controller
$data['include_file'] = $this->load->view('include_view', array(), TRUE);
//Your master view
{$include_file}
```

**Comment by philsturgeon** [comment]
Correct, this is using the Dwoo syntax, not enabling every single feature to work. Do things the CodeIgniter way.
