### ISSUE TITLE
Missing quotations in MY_Parser?

### ISSUE THREAD

**Issue by JoeWesthead** [philsturgeon/codeigniter-dwoo#9]
I'm new to this library, but getting errors immediately on line 158 in MY_Parser.php:

```
Parse error: syntax error, unexpected '[', expecting ')' in /application/libraries/MY_Parser.php on line 158
```

The code appears as so:

```
$string = str_replace(array('{elapsed_time}', '{memory_usage}'), array('[elapsed_time]', [memory_usage]), $string);
```

Putting single quotes around `[memory_usage]` doesn't seem to do the trick, so I'm stuck in the starting blocks.

**Comment by philsturgeon** [comment]
Fixed
